# Deployment Configuration
deployment:
  type: "self_hosted"

base_url: http://localhost:3000

database:
  # url: sqlite:///db/app.db
  url: ${BOW_DATABASE_URL}
  
features:
  allow_uninvited_signups: false
  allow_multiple_organizations: false
  verify_emails: false

auth:
  mode: "hybrid"

google_oauth:
  enabled: false
  client_id: '${BOW_GOOGLE_CLIENT_ID}'
  client_secret: '${BOW_GOOGLE_CLIENT_SECRET}'

oidc_providers:
- name: okta
  enabled: false
  issuer: https://trial-9381896.okta.com/oauth2/default
  client_id: ${OKTA_CLIENT_ID}
  client_secret: ${OKTA_CLIENT_SECRET}
  scopes: ["openid", "profile", "email"]
  pkce: true
  client_auth_method: basic
  discovery: true
  uid_claim: sub
 # Optional overrides:
 # redirect_path: /api/auth/okta/callback
 # extra_authorize_params: { prompt: login }
 # extra_token_params: {}
encryption_key: ${BOW_ENCRYPTION_KEY}

smtp_settings:
  host: "smtp.resend.com"
  port: 587
  username: "resend"
  password: ${BOW_SMTP_PASSWORD}

intercom:
  enabled: true

telemetry:
  enabled: false
